name: Publish to PyPI

on:
  push:
    branches:
      - release  # Trigger on push to any release branch, for example release/v1.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # You can change this to your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine cibuildwheel

      - name: Build the wheels
        env:
          CIBW_SKIP: "pp* *-win32"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux2014_x86_64"
          CIBW_ARCHS_LINUX: "x86_64"
        run: |
          cibuildwheel --output-dir dist

      - name: Publish to PyPI
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD
